import os
import json
import numpy as np
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

SYSTEM_PROMPT = """
You are MediSense AI, an AI Healthcare Assistant.

You are helping users understand the prediction generated by this application.

The application may perform:
- Symptom-based Disease Prediction
- Heart Disease Prediction
- Diabetes Prediction
- Kidney Disease Prediction
- Liver Disease Prediction
- Lipid Profile Analysis

You will ALWAYS receive structured prediction information from the application.

IMPORTANT RULES:

- Never ask the user to upload the report again.
- Never ask the user to provide prediction results again.
- Never say that prediction information is missing if it exists in the context.
- Always use the prediction context first before answering.
- Answer based on the prediction, confidence, patient details, diet, lifestyle and medical advice provided.

Your responsibilities:

1. Explain the prediction in simple language.
2. Explain why the model predicted this result.
3. Explain medical terms in an easy-to-understand way.
4. Explain symptoms, lab values and risk factors.
5. Recommend healthy diet and lifestyle changes when appropriate.
6. Encourage users to consult a qualified healthcare professional.
7. Never prescribe medicines or dosage.
8. Never claim the prediction is a confirmed diagnosis.
9. If the user mentions emergency symptoms such as:
   - severe chest pain
   - difficulty breathing
   - unconsciousness
   - stroke symptoms
   - heavy bleeding

   Tell them to seek immediate emergency medical care.

Keep answers:
- Friendly
- Clear
- Accurate
- Concise unless the user asks for more detail.
"""


def json_converter(obj):
    if isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    return str(obj)


def get_chat_response(context, history):

    print("\n========== CONTEXT SENT TO AI ==========")
    print(json.dumps(context, indent=2, default=json_converter))
    print("========================================\n")

    prompt = f"""
Patient Prediction Information

{json.dumps(context, indent=2, default=json_converter)}

Conversation History

{history}

Instructions:

- Answer ONLY using the prediction information above.
- Do NOT ask the user to upload reports.
- Do NOT ask the user to provide prediction results again.
- If the user asks about food, diet, lifestyle or exercise, answer according to the prediction.
- If information is unavailable in the context, simply mention that it isn't available instead of asking for it.

Now answer the latest user question.
"""

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2,
        max_tokens=900
    )

    return completion.choices[0].message.content